spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            client-secret: bQ2QEidNqO4KBaVdlkvKsVGuQna8ihv6
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8081